### ISSUE TITLE
Installing into 8.7.0 breaks website

### ISSUE THREAD

**Issue by NikRimington** [robertjf/umbMemberListView#14]
Hi Robert,

I've just installed this package into an 8.7.0 Umbraco site and it blows up the site. I've tested this again with a clean install of 8.7.0

The issue is your dependency on Microsoft.AspNet.SignalR.Core version 2.4.1 clashes with Umbraco's dependency on version 2.4.0

This causes a YSOD of 

```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNet.SignalR.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Is there any way your dependency could be dropped down to 2.4.1 to stop this issue happening?

**Comment by robertjf** [comment]
@NikRimington this is resolved as of yesterday with release 2.0.2 if you want to try it out
