### ISSUE TITLE
Remove NotImplementedException

### ISSUE THREAD

**Issue by stefankip** [robertjf/umbMemberListView#18]
Regarding this line:
https://github.com/YourITGroup/MemberListView/blob/921e48dd2b969f93b87a0112bf31a98348522c01/MemberListView/Composing/MemberListViewComponent.cs#L47
Please remove the NotImplementedException, as it is getting logged as an error, while it's perfectly fine to have an empty `Terminate` method.

**Comment by robertjf** [comment]
@stefankip thanks for this, clearly shouldn't be there :) Fixed in latest release (just now)...
