### ISSUE TITLE
Consistency with Umbraco 7.4 style

### ISSUE THREAD

**Issue by bjarnef** [robertjf/umbMemberListView#2]
I think it would be great if the member listview can be updated for future by using e.g. `umb-overlay` directive/component and consistent styling with Umbraco 7.4

Umbraco Forms did something similar where it check agains the Umbraco version variable from server side and if 7.4+ it use `umb-overlay`

Furthermore I noticed that the options in filter dropdown has a text pointer instead of a hand pointer. It is because each anchor inside doesn't have `href` attributes or you could change cursor type via css.

Maybe also just trigger open of the dialog via a link/button in the row, so you still can select rows lik in core listview and click on name redirect to the member detail view.

**Comment by bjarnef** [comment]
Can we using the new listview layout component/directive + umb-overlay for this?

In Umbraco Forms its is doing a check on the version - you could install Umbraco Forms and review the javascript.

E.g.

```
var umbracoVersion = Umbraco.Sys.ServerVariables.application.version;

        $scope.openMediaPicker = function() {

            var compareOptions = {
                zeroExtend: true
            };

            var versionCompare = utilityService.compareVersions(umbracoVersion, "7.4", compareOptions);

            if(versionCompare === 0 || versionCompare === 1) {

                $scope.mediaPickerOverlay = {
                    view: "mediapicker",
                    show: true,
                    submit: function(model) {

                        var selectedImage = model.selectedImages[0];
                        populateFile(selectedImage);

                        $scope.mediaPickerOverlay.show = false;
                        $scope.mediaPickerOverlay = null;
                    }
                };

            } else {

                dialogService.mediaPicker({ callback: populateFile });

            }

        };
```

**Comment by robertjf** [comment]
Hey @bjarnef sounds like an idea; if you would like to do a pull request I'd be happy to review and accept; I haven't the time right at the moment to implement it myself, but would be happy to review a PR in a timely fashion so you won't be left hanging...

A comment about the new listview component/directive - I haven't reviewed; but I'm not sure it would be compatible; I had to implement a custom template for this as it pretty much shares styling only.
