### ISSUE TITLE
Member Export not exporting 

### ISSUE THREAD

**Issue by winterg1979** [robertjf/umbMemberListView#20]
I have used the MemberListView in the past especially the export facility, I have updated to the latest version for Umbraco 7.15.5, and the export doesn't work, I get the slide over window to choose the filters, etc and no matter what options I select when clicking the Export button the window disappears, I get a 500 error for /MemberManager/MemberApi/GetMembersExport?f_mailintlistinclude=1&orderBy=Name&orderDirection=Ascending&format=Excel&columns= am I missing any configuration? Thank you

**Comment by robertjf** [comment]
Hi @winterg1979 can you please check the Umbraco logs and see if there's any additional errors - it's most likely a missing DLL  - could be the ExcelNumberFormat or something like that.

What happens if you install the package via NuGet?  Does that resolve the issue?

https://www.nuget.org/packages/MemberListView/1.5.5

**Comment by winterg1979** [comment]
2021-03-09 17:32:50,303 [P17880/D20/T220] ERROR MemberListView.Controllers.MemberApiController - Unhandled controller exception occurred
System.IO.FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'
   at MemberListView.Extensions.ExportExtension.CreateExcel(IEnumerable`1 list, Stream stream, String sheetName, Boolean includeHeaders)
 
Ok thats what is appearing in the logs, I shall try installing the nuget package later on and see if that is any better.

**Comment by winterg1979** [comment]
So I managed to eventually install the nuget package, was still having some issues related to my setup, I ended up uninstalling ClosedXML and DocumentFormat.OpenXML and then restinstalling ClosedXML version 0.94.2 and accepting the version of OpenXML it gave me which was 2.7.2.0 and the export is working. Thanks for your help.
