### ISSUE TITLE
How to export Selected Users

### ISSUE THREAD

**Issue by nnahmed** [robertjf/umbMemberListView#21]
Hi 

How we can export only the selected user from the user list?

![image](https://user-images.githubusercontent.com/8067853/119266404-be5ec780-bbfb-11eb-8e9f-60aab51047ef.png)

Thanks

**Comment by robertjf** [comment]
Currently, you can't - the export uses the current filter to export all members in the list if one is applied, not only the current page.

**Comment by nnahmed** [comment]
Thank you Robert for quick response appreciated.
 
Can you help me, if there anyway we can get information of these selected users in the MemberListView Plugin?

Your support will be really helpful. 

Thanks

**Comment by robertjf** [comment]
@nnahmed can you expand on what you mean by get information of selected users?

**Comment by nnahmed** [comment]
I means, i selected 3 users from the users grid by making selection. I only want to export that. Can i get those selected members, Member id  information in the Members list view

**Comment by robertjf** [comment]
you have two options here - use the Filter to filter the members that you want to export.

Or, modify the source code to add an additional export button to only export selected members (and commit a pull request to have your change included in the project 😎 )

I've added the Enhancement label as I think this is a good idea, but I don't have free time to work on it myself at the moment.

**Comment by robertjf** [comment]
This is now supported on Umbraco 10 & 11 as of Version 3.0.0
