### ISSUE TITLE
Sort and Filtering not working well.

### ISSUE THREAD

**Issue by ivan-balio** [robertjf/umbMemberListView#22]
Hi there?
Good Day!

I found the issue where you can't filter and sort the member list view properly. I tried to edit the back-end javascript and realized it will be over written in the future update. 

![sortingprob01](https://user-images.githubusercontent.com/70715171/120793936-1be30480-c56a-11eb-84c3-49e58e858176.PNG)
![sortprob02](https://user-images.githubusercontent.com/70715171/120793940-1dacc800-c56a-11eb-8af0-7d9ec58de313.PNG)

![l;atestumbraco](https://user-images.githubusercontent.com/70715171/120799878-dd514800-c571-11eb-8a66-d1c14815fc70.PNG)

Thanks,
Ivan

**Comment by robertjf** [comment]
@ivan-balio can you provide a pull request with your code changes?  That would be the easiest way to ensure the code changes don't get overwritten in a future update :)

**Comment by ivan-balio** [comment]
Hi Robert,

I did not customized the plugin instead I installed it in my umbraco version 8.13.1 but did not work well. Please refer to the memberlist plugin below. I just did download it from the github repo.

[MemberListView-master.zip](https://github.com/YourITGroup/MemberListView/files/6608113/MemberListView-master.zip)

Thanks.
