### ISSUE TITLE
XLSX Export doesn´t work

### ISSUE THREAD

**Issue by ChristophClaus** [robertjf/umbMemberListView#23]
Hello, 

I have installed the package via the Umbraco backend. The XLSX export does not work - the CSV export does. What can be the problem? In Chrome Dev-tools I see an Internal Server Error 500 at /umbraco/backoffice/MemberListView/ExtendedMember/GetExportedMembers?orderBy=email&orderDirection=Ascending&orderBySystemField=true&format=Excel&columns= [...]

I have another question: how can I customize the member list view? I would like to show more or different columns.

Thanks and best regards
Christoph Claus

**Comment by robertjf** [comment]
Hi Christoph,
First thing to check with the Excel export is that the correct dlls are installed - it's a very specific version of the  ClosedXML NuGet package to work correctly.   Also, check the Umbraco logs for the actual error.
