### ISSUE TITLE
Fail after install

### ISSUE THREAD

**Issue by snowlers** [robertjf/umbMemberListView#33]
I'm running 10.2.1 of Umbraco and tried to install this package. When I try to start the website it fails at startup and nothing works until I uninstall MemberListView. Is this compatible with version 10? 

`ReflectionTypeLoadException: Could not load all types from "MemberListView, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping: . System.TypeLoadException on Umbraco.Cms.Core.Services.Implement.MemberService: Could not load type 'Umbraco.Cms.Core.Services.Implement.MemberService' from assembly 'Umbraco.Infrastructure, Version=10.2.1.0, Culture=neutral, PublicKeyToken=null'. Could not load type 'Umbraco.Cms.Core.Services.Implement.MemberService' from assembly 'Umbraco.Infrastructure, Version=10.2.1.0, Culture=neutral, PublicKeyToken=null'.
Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses, Func<Type, bool> additionalFilter)
Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType<T>(ITypeFinder typeFinder, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Cms.Core.Composing.TypeLoader+<>c__DisplayClass21_0<T>.<GetTypes>b__0()
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypes<T>(bool cache, IEnumerable<Assembly> specificAssemblies)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
uAdventist.Site.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            services.AddUmbraco(_env, _config)
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, object instance)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Microsoft.Extensions.Hosting.HostBuilder.Build()
Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
uAdventist.Site.Program.Main(string[] args) in Program.cs
+
            => CreateHostBuilder(args)
`

**Comment by robertjf** [comment]
@snowlers currently not, no - we will be releasing a compatible version in the future though.

**Comment by robertjf** [comment]
There's a pre-release version 3.0.0 going onto nuget shortly that is compatible with Umbraco 10 and 11

**Comment by snowlers** [comment]
@robertjf thanks for making it compatible with 11. Now when I install it there is no error message, but I can't find the added list/dashboard in the member section. It looks the same as before I installed the package. Is there something that I need to do in order for it to show up? 

Using ver 3.0.2 on umbraco 11.2

**Comment by robertjf** [comment]
It might be a caching issue - are there any errors reported in the Developer Tools console for the browser?

**Comment by snowlers** [comment]
Thanks for reply. I have restarted everything. No errors in the console. The JS files seems to load at least. Maybe I'm not understanding where it should show up... including two screenshots of the sources and what my member area looks like.

![memberlistview](https://user-images.githubusercontent.com/2520275/223807821-36a9982f-cbf9-45f0-b173-b0ca59450e73.png)

![memberlistview2](https://user-images.githubusercontent.com/2520275/223807931-19d95300-6cdc-4930-b328-2d2d90f12a7b.png)

**Comment by robertjf** [comment]
Hi @snowlers the Member List View is a dashboard only, it doesn't affect the individual member lists (yet) although that is a feature I have been meaning to implement!

**Comment by snowlers** [comment]
Hi @robertjf and thanks for your work. I finally found the functionality, my bad. Thought there would be a new item in the left column or something. Looks great. How hard would it be to allow filtering on groups in addition to what you have done already? That would come in real handy I think when we will handle a large amount of members. I'm new to Umbraco so there is a lot to learn how things are working.

**Comment by robertjf** [comment]
@snowlers try out the filtering in the new member list view dashboard - it should support member groups out of the box...

**Comment by snowlers** [comment]
Hmm, where do I find the "new" list? Here is what my filter dialog looks like in the latest version 3.0.2
![filter](https://user-images.githubusercontent.com/2520275/224131256-c2485518-359b-4f33-8875-3657d2fae49e.png)

**Comment by robertjf** [comment]
hm.  Maybe it was a customisation I did for someone else (paid job - was an earlier version)... I don't have the time at the moment but can add it in at some stage.

**Comment by robertjf** [comment]
Or, how many groups do you have defined?  If there's only one, then it's probably not showing up.. I don't remember - will need to take a look at the code.

**Comment by snowlers** [comment]
Yeah! You were right, as soon as I added another group it showed up. Thanks for your quick responses and for making the plugin :)
