### ISSUE TITLE
Member delete confirmation button cannot be clicked

### ISSUE THREAD

**Issue by joris-peters** [robertjf/umbMemberListView#34]
Hi! We are running into an issue when deleting members using the member list.

Issue:

When deleting a member the confirmation button is overlapped by an UI overlay. The button is visible but the button cannot be clicked. Clicking the button clicks the UI overlay instead of the button. I have attached a screenshot to illustrate this issue.

Steps to reproduce:

1. Navigate to Umbraco backoffice
2. Navigate to Members section
3. Navigate to Members in the content tree
4. Click a member's name to open the infinite member editor
5. Click Actions and then Delete
6. The confirmation button is now visible ("Are you sure you want to delete [member]?") but it cannot be clicked

Package version: 2.3.0
Umbraco version: 8.18.5
Browser: Google Chrome 107.0.5304.123

Any assistance in resolving the issue would be much appreciated. Please let me know if further information is needed.

![image](https://user-images.githubusercontent.com/97341161/205658289-3f6cbbd5-da2c-49ea-9529-8c9b8349d77d.png)

**Comment by robertjf** [comment]
Hi @joris-peters - try to identify the html element that's overlaid on the delete dialog - where is that coming from?  You may have to use Dev Tools (F12) to find out.

**Comment by robertjf** [comment]
@joris-peters I've been able to replicate this - the issue is that the infinite editor overrides the delete dialog - something that's an issue with Umbraco itself it seems.  The work around is to select the member in the list view and use the delete button there.

**Comment by robertjf** [comment]
I've logged a bug with Umbraco about this... https://github.com/umbraco/Umbraco-CMS/issues/13623
