### ISSUE TITLE
Unable to export members

### ISSUE THREAD

**Issue by D-Inventor** [robertjf/umbMemberListView#44]
Using Umbraco 10.5.1 and MemberListView 3.0.2

When attempting to use the member export feature, the feature fails to work when pressing the export button with an error in the DevTools:
![image](https://github.com/YourITGroup/MemberListView/assets/25585418/7c298b94-10d7-48fd-aedb-f33661305364)

### Steps to reproduce:
1. Install Umbraco 10.5.1 and MemberListView 3.0.2
2. Make some members in the members section to export
3. press the "Export Members" button
4. Select some fields in the menu that opens up.
5. Press the "Export" button at the bottom of the menu
6. Observe the error in the DevTools

### What I expected to happen:
After pressing the "Export" button, I expected a download to start or at least some continuation, not an error.

**Comment by robertjf** [comment]
Hi @D-Inventor, do you have any custom properties on the Member type?  Also, can you verify whether filtering members is working correctly?

**Comment by D-Inventor** [comment]
Hi @robertjf ! I do have some custom properties on the Member type! They are a simple text field, a readonly field and a datetime field. Filters seem to work as expected.

**Comment by robertjf** [comment]
@D-Inventor this has now been fixed in the most recent release 3.0.3 - let me know if you are still encountering problems!
