### ISSUE TITLE
Dependencies with Latest Version of Umbraco

### ISSUE THREAD

**Issue by tbraz** [robertjf/umbMemberListView#6]
Your package depends on ClientDependency-Mvc while UmbracoCms.Core depends on ClientDependency-Mvc5 (UmbracoCms.Core:7.10.4 at the time of this writing).  
I know for sure that once I've added your Nuget to my project it no longer ran due to those issues.  

Can you package a new version with those dependencies fixed?
Thank you

**Comment by robertjf** [comment]
Thanks for bringing this to my attention - I'm removing the old dependency as it's no longer needed; you can force the removal in your own installation safely without affecting anything.

A new Nuget package 1.2.1 will be  released just as soon as it's been validated on nuget.org

ta,
Rob
