### ISSUE TITLE
You have unsaved changes... Popup always appears after switching another tab

### ISSUE THREAD

**Issue by trannamquan** [robertjf/umbMemberListView#7]
I go to manage tab. I approve or suspend or delete any member, everything works perfect. Until I switch to another tab, the popup "You have unsaved changes..." appears with 2 buttons "Discard changes" and "Stay".
 If I choose "Discard changes", everything still fine, the actions I made are applied. 
 If I choose "Stay", at this manage view, there is no save button like others umbraco pages. I can get out this manage view. So the only option is choose "Discard changes"

So how can I turn off this popup for this package. Or, a save button should be there like the other pages.

Current Umbraco version: 7.12.0

**Comment by robertjf** [comment]
This is now fixed; and I've also added package-level lang/*.xml files so certain labels can be localized.
